{
 "title": "Client credentials SLO",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod_name",
    "query": {
     "query": "http_server_requests_seconds_bucket{namespace=\"$namespace\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "$pod_name stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod_name" },
  {
   "title": "$pod_name - Below 50ms response time percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_bucket{uri=\"/realms/{realm}/protocol/{protocol}/token\", le=\"0.05\", namespace=\"$namespace\", pod=\"$pod_name\"}[2m])) without (le) / rate(http_server_requests_seconds_count{uri=\"/realms/{realm}/protocol/{protocol}/token\", namespace=\"$namespace\", pod=\"$pod_name\"}[2m])",
     "legendFormat": "Percentage below 50ms"
    },
    {
     "expr": "rate(vendor_statistics_hits{cache=\"realms\", namespace=\"${namespace}\", pod=\"$pod_name\"}[2m]) / (rate(vendor_statistics_hits{cache=\"realms\", namespace=\"${namespace}\", pod=\"$pod_name\"}[2m]) + rate(vendor_statistics_misses{cache=\"realms\", namespace=\"${namespace}\", pod=\"$pod_name\"}[2m]))",
     "legendFormat": "Realms cache hit ratio"
    },
    {
     "expr": "rate(vendor_statistics_hits{cache=\"users\", namespace=\"${namespace}\", pod=\"$pod_name\"}[2m]) / (rate(vendor_statistics_hits{cache=\"users\", namespace=\"${namespace}\", pod=\"$pod_name\"}[2m]) + rate(vendor_statistics_misses{cache=\"users\", namespace=\"${namespace}\", pod=\"$pod_name\"}[2m]))",
     "legendFormat": "Users cache hit ratio"
    }
   ]
  },
  {
   "title": "$pod_name - Response time histogram",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by (le) (idelta(http_server_requests_seconds_bucket{uri=\"/realms/{realm}/protocol/{protocol}/token\", namespace=\"$namespace\", pod=\"$pod_name\"} [2m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$pod_name - 99 quantile millis",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{uri=\"/realms/{realm}/protocol/{protocol}/token\", namespace=\"$namespace\", pod=\"$pod_name\"}[2m])) by (le,uri))",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}